// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtL4WJbPfvk_tdped8IDwImLmu9H37xE0',
    appId: '1:209706329218:web:b52d6706d8f0224f65809b',
    messagingSenderId: '209706329218',
    projectId: 'emergencyresponsesystem-166601',
    authDomain: 'emergencyresponsesystem-166601.firebaseapp.com',
    storageBucket: 'emergencyresponsesystem-166601.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2ZRj26RCiYESHlb2uad_dEZz6hWRtIw',
    appId: '1:209706329218:android:3ea556fe5bb62f5b65809b',
    messagingSenderId: '209706329218',
    projectId: 'emergencyresponsesystem-166601',
    storageBucket: 'emergencyresponsesystem-166601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcuvctzK3WQJ_5zUSCByl6CFQloUiWrOU',
    appId: '1:209706329218:ios:c3c40d384819f05865809b',
    messagingSenderId: '209706329218',
    projectId: 'emergencyresponsesystem-166601',
    storageBucket: 'emergencyresponsesystem-166601.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcuvctzK3WQJ_5zUSCByl6CFQloUiWrOU',
    appId: '1:209706329218:ios:c3c40d384819f05865809b',
    messagingSenderId: '209706329218',
    projectId: 'emergencyresponsesystem-166601',
    storageBucket: 'emergencyresponsesystem-166601.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtL4WJbPfvk_tdped8IDwImLmu9H37xE0',
    appId: '1:209706329218:web:65876e4bd5759aa165809b',
    messagingSenderId: '209706329218',
    projectId: 'emergencyresponsesystem-166601',
    authDomain: 'emergencyresponsesystem-166601.firebaseapp.com',
    storageBucket: 'emergencyresponsesystem-166601.firebasestorage.app',
  );
}
